---
- hosts: cluster
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - name: Setup incus server(s)
      ansible.builtin.import_role:
        name: incus
      tags: cluster

- name: Deploying Colosseum
  hosts: localhost
  gather_facts: false
  connection: local
  tags: infrastructure
  roles:
    - role: terraform
      tags: infrastructure
  vars:
    cluster_address: "{{ hostvars[groups['cluster'][0]]['ansible_host']}}"
    nodes: "{{ groups['cluster'] }}"
    instances_type: "container"
    project_name: "ColosseumCTF"

# - name: Configuring router of the game network
#   hosts: router
#   gather_facts: false
#   roles:
#     - router
# 
# - name: "Configuring Vulnboxes"
#   hosts: vulnboxes
#   gather_facts: false
#   roles:
#     - vulnboxes
#   tasks:
#     - name: "Get address from router"
#       systemd_service:
#         name: systemd-networkd
#         state: restarted
