namespace: colosseum
name: colosseum

description: Roles to deploy colosseum, an Attack and Defense infrastructure inspiride by CyberChallenge
version: 1.0

authors:
  - Giuliano Vallone

readme: README.md

repository: https://github.com/hackerinotopolino/colosseum-ctf
issues: https://github.com/hackerinotopolino/colosseum-ctf/issues
homepage: https://github.com/hackerinotopolino/colosseum-ctf

tags:
  - ctf
  - clustering
  - security
  - installer
  - debian
  - python
  - incus

dependencies:
  fausecteam.ctf_gameserver_ansible
