- name: Generate client private key
  shell: wg genkey
  register: client_private_key

- name: Generate client public key
  shell: "echo -n '{{ client_private_key.stdout }}' | wg pubkey"
  register: client_public_key

- name: Set client Address
  set_fact:
    client_address: "10.80.{{ teams.index(player.0) + 1 }}.{{ player.1 }}"

- name: "Generate client configuration"
  local_action:
    module: template
    src: wg0_client.conf.j2
    mode: 0600
    dest: "out/vpns/{{ player.0 }}/player{{ player.1 }}.conf"
    force: true

- name: "Adding Peer to the wireguard server"
  lineinfile:
    path: /etc/wireguard/wg0.conf
    line: "[Peer]\nPublicKey = {{ client_public_key.stdout }}\nAllowedIPs = {{ client_address }}/32\n"
    insertafter: EOF


