---
- name: Generate ssh key for admins
  community.crypto.openssh_keypair:
    path: "out/colosseum_admin"
    type: ed25519
    force: true
  run_once: true
  delegate_to: localhost
  connection: local

- name: Copy host ssh key on the vulnbox
  ansible.posix.authorized_key:
    user: root
    key: "{{ lookup('file', 'out/colosseum_admin.pub') }}"

- name: Create random password
  ansible.builtin.set_fact:
    vulnbox_root_password: >
      "{{ lookup('ansible.builtin.password',
      '/dev/null',
      seed=inventory_hostname) }}"

- name: Set the generated password as root password
  ansible.builtin.user:
    name: root
    password: "{{ vulnbox_root_password | password_hash('sha512') }}"

- name: Create Output Direcotry
  ansible.builtin.file:
    path: "out/vm_passwords"
    state: directory
    mode: "0755"
  delegate_to: localhost
  connection: local

- name: Save the password to a local file
  ansible.builtin.copy:
    content: "{{ vulnbox_root_password }}\n"
    dest: "out/vm_passwords/{{ inventory_hostname }}.txt"
    mode: "0644"
  delegate_to: localhost
  connection: local
