---
- name: Deploy of the AD platform
  community.general.terraform:
    project_path: "{{ role_path }}/files/colosseum-infrastructure"
    force_init: true
    state: present
    complex_vars: true
    no_color: true
    provider_upgrade: true
    variables:
      cluster_address: "{{ cluster_address }}"
      instances_type: "{{ instances_type }}"
      remote: "{{ remote }}"
      teams: "{{ teams }}"
      nodes: "{{ nodes }}"
  run_once: true
  delegate_to: localhost
  connection: local
