- hosts: localhost
  gather_facts: false
  connection: local
  roles:
    - { role: colosseum/terraform }

- hosts: router
  gather_facts: false
  roles:
    - { role: colosseum/router }

- hosts: vulnboxes
  gather_facts: false
  roles:
    - { role: colosseum/vulnboxes }
  tasks:
    - name: "Get address from router"
      systemd_service:
        name: systemd-networkd
        state: restarted

