- hosts: localhost
  gather_facts: false
  connection: local
  roles:
    - { role: colosseum/terraform }

- hosts: vulnboxes
  gather_facts: false
  roles:
    - { role: colosseum/vulnboxes }
 
- hosts: wireguard_servers
  gather_facts: false
  roles:
    - { role: colosseum/wireguard_servers }

